name: Testing
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample: [opendialog, opendialogmultiple, pickfolder, savedialog]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Installing Dependencies
        run: sudo apt-get install libgtk-3-dev

      - name: Config Dependencies
        run: pkg-config --cflags --libs gtk+-3.0

      - name: Compiling 
        run: |
          haxelib git hxnativefiledialog https://github.com/MAJigsaw77/hxnativefiledialog.git ${{github.ref_name}} --quiet
          cd samples/${{matrix.sample}}
          haxe build.hxml
